---
version: '3'

volumes:
  uptimekuma-data:
    driver: local

services:
  uptimekuma:
    image: louislam/uptime-kuma:1.22.1
    container_name: uptimekuma
    hostname: uptimekuma
    # command: sudo sysctl -w net.core.rmem_max=2500000 && sudo sysctl -w net.core.wmem_max=2500000
    # Expose these ports for local access to GUI
    ports:
      - "3001:3001"
    volumes:
      - uptimekuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UPTIME_KUMA_CLOUDFLARED_TOKEN=${CF_TOKEN}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.monitor-only: true

  watchtower:
    image: containrrr/watchtower:1.5.3
    container_name: watchtower-oci
    hostname: oci-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Copenhagen
      - WATCHTOWER_POLL_INTERVAL=43200
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${notifi_webhook}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.monitor-only: true

  # jekyll:
  #   image: jekyll/jekyll:4.2.2
  #   container_name: jekyll
  #   hostname: jekyll
  #   volumes:
  #     - /home/ubuntu/CV:/srv/jekyll:Z
  #   ports:
  #     - "4000:4000"
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   networks:
  #     - proxy
  #   command: jekyll serve

  jekyll:
    image: avhost/docker-jekyll:master
    container_name: jekyll
    hostname: jekyll
    ports:
      - "80:8888"
    environment:
      - GIT_REPO=https://github.com/aleksanderbl29/CV
    networks:
      - proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true


networks:
  proxy:
    external: true


# docker run --rm \
#   --volume="$PWD:/srv/jekyll:Z" \
#   --publish [::1]:4000:4000 \
#   jekyll/jekyll \
#   jekyll serve
