---
version: '2'
services:
  gatus:
    image: twinproduction/gatus:v5.8.0
    restart: unless-stopped
    ports:
      - "9384:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER} # postgres user with access to the database
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # postgres user password
      - POSTGRES_DB=${POSTGRES_GATUS_DB} # this should be the name of your postgres database
    volumes:
      - ./config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.gatus.entrypoints: http
      traefik.http.routers.gatus.rule: Host(`gatus.local.aleksanderbl.dk`)
      traefik.http.middlewares.gatus-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.gatus.middlewares: gatus-https-redirect
      traefik.http.routers.gatus-secure.entrypoints: https
      traefik.http.routers.gatus-secure.rule: Host(`gatus.local.aleksanderbl.dk`)
      traefik.http.routers.gatus-secure.tls: true
      traefik.http.routers.gatus-secure.service: gatus
      traefik.http.services.gatus.loadbalancer.server.port: 8080
      traefik.docker.network: proxy

      com.centurylinklabs.watchtower.monitor-only: true
    networks:
      - proxy
      - database

networks:
  database:
    external: true
  proxy:
    external: true
