---
version: "2"

services:
  bind9:
    container_name: bind9-prod-1
    image: ubuntu/bind9:9.18-23.04_edge
    environment:
      - BIND9_USER=root
      - TZ=Europe/Copenhagen
    volumes:
      - ./config/:/etc/bind:rw
    ports:
      - 53:53/tcp
      - 53:53/udp
    restart: unless-stopped
