---
version: '3'

services:
  gitea:
    image: gitea/gitea:1.21.10
    container_name: gitea
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - GITEA__database__DB_TYPE=${GITEA__database__DB_TYPE}
      - GITEA__database__HOST=${GITEA__database__HOST}
      - GITEA__database__NAME=${GITEA__database__NAME}
      - GITEA__database__USER=${GITEA__database__USER}
      - GITEA__database__PASSWD=${GITEA__database__PASSWD}
    volumes:
      # - ./data:/var/lib/gitea
      # - ./config:/etc/gitea
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    #   - "22:22"
    #   - "2222:2222"
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.entrypoints: http
      traefik.http.routers.gitea.rule: Host(`git.local.aleksanderbl.dk`)
      traefik.http.middlewares.gitea-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.gitea.middlewares: gitea-https-redirect
      traefik.http.routers.gitea-secure.entrypoints: https
      traefik.http.routers.gitea-secure.rule: Host(`git.local.aleksanderbl.dk`)
      traefik.http.routers.gitea-secure.tls: true
      traefik.http.routers.gitea-secure.service: gitea
      traefik.http.services.gitea.loadbalancer.server.port: 3000
      traefik.docker.network: proxy

      com.centurylinklabs.watchtower.monitor-only: true

networks:
  proxy:
    external: true
