version: '2'

services:
  gitea:
    image: gitea/gitea:1.21.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /mnt/media/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      # - "22:22"
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.entrypoints: http
      traefik.http.routers.gitea.rule: Host(`gitea.local.aleksanderbl.dk`)
      traefik.http.middlewares.gitea-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.gitea.middlewares: gitea-https-redirect
      traefik.http.routers.gitea-secure.entrypoints: https
      traefik.http.routers.gitea-secure.rule: Host(`gitea.local.aleksanderbl.dk`)
      traefik.http.routers.gitea-secure.tls: true
      traefik.http.routers.gitea-secure.service: gitea
      traefik.http.services.gitea.loadbalancer.server.port: 8080
      traefik.docker.network: proxy

      com.centurylinklabs.watchtower.monitor-only: true

networks:
  proxy:
    external: true
