---
storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_IP}:5432/${POSTGRES_DB}?sslmode=disable"

alerting:
  github:
    repository-url: "https://github.com/aleksanderbl29/homelab"
    token: "${GITHUB_TOKEN}"
    default-alert:
      failure-threshold: 20
      success-threshold: 5
      send-on-resolved: true
      description: "This is an automated health check message. It will automatically be removed if it is resolved."
  matrix:
    server-url: "https://matrix-client.matrix.org"
    access-token: "${MATRIX_ACCESS_TOKEN}"
    internal-room-id: "${MATRIX_INTERNAL_ROOM_ID}"
    default-alert:
      description: "health check failed"
      send-on-resolved: true
      failure-threshold: 1
      success-threshold: 2
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}
    default-alert:
      failure-threshold: 2
      success-threshold: 2
      send-on-resolved: true

endpoints:
  - name: hjemmeside
    group: web
    url: "https://aleksanderbl.dk"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: github
        repository-url: "https://github.com/aleksanderbl29/aleksanderbldk"

  - name: google.dk
    group: infra
    url: "1.1.1.1" # Address of the DNS server to use
    interval: 3m
    dns:
      query-name: "google.dk"
      query-type: "A"
    conditions:
      - "[BODY] == 142.251.9.94"
      - "[DNS_RCODE] == NOERROR"
    alerts:
      # - type: matrix
      - type: slack
