---
version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /home/aleksanderbang-larsen/homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.homeassistant.entrypoints: http
      traefik.http.routers.homeassistant.rule: Host(`ha-test.local.aleksanderbl.dk`)
      traefik.http.middlewares.homeassistant-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.homeassistant.middlewares: homeassistant-https-redirect
      traefik.http.routers.homeassistant-secure.entrypoints: https
      traefik.http.routers.homeassistant-secure.rule: Host(`ha-test.local.aleksanderbl.dk`)
      traefik.http.routers.homeassistant-secure.tls: true
      traefik.routers.homeassistant-secure.service: homeassistant
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123
      traefik.docker.network: proxy2
    networks:
      - proxy2
    security_opt:
      - no-new-privileges:true
    privileged: true
    # network_mode: host
    ports:
      - 8123:8123

networks:
  proxy2:
    external: true
