---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.10
    container_name: homepage
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    # ports:
    #   - 3000:3000
    env_file:
      - .env
    volumes:
      - ./config:/app/config # Directory for config files
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

    labels:
      traefik.enable: true
      traefik.http.routers.dash.entrypoints: http
      traefik.http.routers.dash.rule: Host(`dash.local.aleksanderbl.dk`)
      traefik.http.middlewares.dash-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.dash.middlewares: dash-https-redirect
      traefik.http.routers.dash-secure.entrypoints: https
      traefik.http.routers.dash-secure.rule: Host(`dash.local.aleksanderbl.dk`)
      traefik.http.routers.dash-secure.tls: true
      traefik.http.routers.dash-secure.service: dash
      traefik.http.services.dash.loadbalancer.server.port: 3000
      traefik.docker.network: proxy

      com.centurylinklabs.watchtower.monitor-only: true

networks:
  proxy:
    external: true
