---
services:
  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower-monitor
    hostname: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Copenhagen
      - WATCHTOWER_POLL_INTERVAL=${polling}
      - WATCHTOWER_NOTIFICATIONS=${notifi_service}
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${webhook}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=${log_level}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

networks:
  proxy:
    external: true
