version:  "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Copnehagen
      - WATCHTOWER_POLL_INTERVAL36000
      - WATCHTOWER_NOTIFICATIONS=${notifi_service}
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${webhook}
