---
version: '2'
services:
  homer:
    image: b4bz/homer:v23.10.1
    container_name: homer
    hostname: homer
    volumes:
      - /home/aleksanderbang-larsen/homelab/dashboard/assets/:/www/assets
    # ports:
    #   - 8080:8080
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

    labels:
      traefik.enable: true
      traefik.http.routers.homer.entrypoints: http
      traefik.http.routers.homer.rule: Host(`homer.local.aleksanderbl.dk`)
      traefik.http.middlewares.homer-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.homer.middlewares: homer-https-redirect
      traefik.http.routers.homer-secure.entrypoints: https
      traefik.http.routers.homer-secure.rule: Host(`homer.local.aleksanderbl.dk`)
      traefik.http.routers.homer-secure.tls: true
      traefik.http.routers.homer-secure.service: dash
      traefik.http.services.homer.loadbalancer.server.port: 8080
      traefik.docker.network: proxy

      com.centurylinklabs.watchtower.monitor-only: true

networks:
  proxy:
    external: true
