---
version: '3'
services:
  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    container_name: littlelink-server
    hostname: littlelink-server
    environment:
      - META_TITLE=Aleksander's little links
      - META_DESCRIPTION=Aleksanders små links
      - META_AUTHOR=Aleksander Bang-Larsen
      - THEME=Dark
      - FAVICON_URL=https://pbs.twimg.com/profile_images/1661137669156487168/VcAtkav1_400x400.jpg
      - AVATAR_URL=https://pbs.twimg.com/profile_images/1661137669156487168/VcAtkav1_400x400.jpg
      - AVATAR_2X_URL=https://pbs.twimg.com/profile_images/1661137669156487168/VcAtkav1_400x400.jpg
      - AVATAR_ALT=Aleksander's profile pic
      - NAME=Aleksander's links
      - BIO=Hey! Here is all of my links!
      - GITHUB=https://github.com/aleksanderbl29
      - TWITTER=https://twitter.com/bang_aleksander
      - INSTAGRAM=https://www.instagram.com/aleksanderbl/
      # - YOUTUBE=https://l.technotim.live/subscribe
      # - TWITCH=https://l.technotim.live/twitch/
      # - DISCORD=https://l.technotim.live/discord
      # - TIKTOK=https://l.technotim.live/tiktok
      # - KIT=https://l.technotim.live/gear
      # - FACEBOOK=https://facebook.com
      # - FACEBOOK_MESSENGER=https://facebook.com
      - LINKED_IN=https://www.linkedin.com/in/aleksander-bang-larsen-405b03a4/
      # - PRODUCT_HUNT=https://www.producthunt.com/
      # - SNAPCHAT=https://www.snapchat.com/
      # - SPOTIFY=https://www.spotify.com/
      # - REDDIT=https://www.reddit.com/
      # - MEDIUM=https://medium.com
      # - PINTEREST=https://www.pinterest.com/
      - EMAIL=aleksanderbl@live.dk
      # - EMAIL_ALT=you@example.com
      # - SOUND_CLOUD=https://souncloud.com
      # - FIGMA=https://figma.com
      # - TELEGRAM=https://telegram.org/
      # - TUMBLR=https://www.tumblr.com/
      # - STEAM=https://steamcommunity.com/
      # - VIMEO=https://vimeo.com/
      # - WORDPRESS=https://wordpress.com/
      # - GOODREADS=https://www.goodreads.com/
      # - SKOOB=https://www.skoob.com.br/
      # use ENV variable names for order, listed buttons will be boosted to the top
      - BUTTON_ORDER=YOUTUBE,TWITCH,TWITTER,GITHUB,INSTAGRAM,LINKED_IN,DISCORD,FACEBOOK,TIKTOK,PATREON,GEAR,,THESTUDENTTRAVELLER,STATUS,DOCUMENTATION
      # you can render an unlimited amount of custom buttons by adding
      # the CUSTOM_BUTTON_* variables and by using a comma as a separator.
      - CUSTOM_BUTTON_TEXT=Documentation,Status,The Student Traveller
      - CUSTOM_BUTTON_URL=https://docs.aleksanderbl.dk,https://uptime.aleksanderbl.dk,https://thestudenttraveller.dk
      - CUSTOM_BUTTON_COLOR=#000000,#000000,#000000
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff,#ffffff,#ffffff
      - CUSTOM_BUTTON_ALT_TEXT=Documentation for my homelab,Status page for my services,My friend's great travel blog
      - CUSTOM_BUTTON_NAME=DOCUMENTATION,STATUS,THESTUDENTTRAVELLER
      - CUSTOM_BUTTON_ICON=fas file-alt,fa-solid fa-stethoscope,fas plane
      - FOOTER=Aleksander Bang-Larsen © 2023
      - SKIP_HEALTH_CHECK_LOGS=true
      - GA_TRACKING=ID=${GA_TRACKING_ID}
    ports:
      - 8089:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.littlelink.entrypoints: http
      traefik.http.routers.littlelink.rule: Host(`links.local.aleksanderbl.dk`)
      traefik.http.middlewares.littlelink-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.littlelink.middlewares: littlelink-https-redirect
      traefik.http.routers.littlelink-secure.entrypoints: https
      traefik.http.routers.littlelink-secure.rule: Host(`links.local.aleksanderbl.dk`)
      traefik.http.routers.littlelink-secure.tls: true
      traefik.http.routers.littlelink-secure.service: littlelink
      traefik.http.services.littlelink.loadbalancer.server.port: 3000
      traefik.docker.network: proxy
      com.centurylinklabs.watchtower.monitor-only: true

networks:
  proxy:
    external: true
