---
version: '3'

services:
  portainer_agent:
    image: portainer/agent:2.19.0
    container_name: portainer_agent
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
