version: '2'

services:
  cf-tunnel:
    image: erisamoe/cloudflared:2023.10.0
    container_name: cloudflare-tunnel
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${cf-token}
    networks:
      - external

networks:
  external:
    external: true
