---
services:
  cf-tunnel:
    image: erisamoe/cloudflared:2024.7.1
    container_name: cloudflare-tunnel
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - external
    env_file:
      - .env

  # cloudflare-ddns:
  #   image: oznu/cloudflare-ddns:latest
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   env_file:
  #     - .env
  #   environment:
  #     - API_KEY=${CF_API_KEY}
  #     - ZONE=aleksanderbl.dk
  #     - SUBDOMAIN=ddns
  #     - PROXIED=true

networks:
  external:
    external: true
