version: '3'

volumes:
  uptimekuma-data:
    driver: local

services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    hostname: uptimekuma
    ## Expose these ports for local access to GUI
    # ports:
    #   - "3001:3001"
    volumes:
      - uptimekuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UPTIME_KUMA_CLOUDFLARED_TOKEN=${CF_TOKEN}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  ###### Virker kun på x86
  # backup:
  #   image: jareware/docker-volume-backup
  #   volumes:
  #     - uptimekuma-data:/backup/uptimekuma-data:ro           # Mount the Grafana data volume (as read-only)
  #     - /home/aleksanderbang-larsen/backups:/archive         # Mount a local folder as the backup archive
