---
volumes:
  uptimekuma-data:
    driver: local

services:
  uptimekuma:
    image: louislam/uptime-kuma:1.23.16     ## force this specific version 1.23.3
    container_name: uptimekuma
    hostname: uptimekuma
    ## Expose these ports for local access to GUI
    # ports:
    #   - "3001:3001"
    volumes:
      - uptimekuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UPTIME_KUMA_CLOUDFLARED_TOKEN=${CF_TOKEN}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

    labels:
      traefik.enable: true
      traefik.http.routers.uptime.entrypoints: http
      traefik.http.routers.uptime.rule: Host(`uptime.local.aleksanderbl.dk`)
      traefik.http.middlewares.uptime-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.uptime.middlewares: uptime-https-redirect
      traefik.http.routers.uptime-secure.entrypoints: https
      traefik.http.routers.uptime-secure.rule: Host(`uptime.local.aleksanderbl.dk`)
      traefik.http.routers.uptime-secure.tls: true
      traefik.http.routers.uptime-secure.service: uptime
      traefik.http.services.uptime.loadbalancer.server.port: 3001
      traefik.docker.network: proxy

      com.centurylinklabs.watchtower.monitor-only: true

networks:
  proxy:
    external: true
