version: '3'

volumes:
  uptimekuma-data:
    driver: local

services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    ## Temporarily removed ports to test cloudflared
    # ports:
    #   - "3001:3001"
    volumes:
      - uptimekuma-data:/app/data
    environment:
      - UPTIME_KUMA_CLOUDFLARED_TOKEN=${CF_TOKEN}
    # env_file: ## For passing through cloudflare token
    #   - .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true