---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Smart Home:
    - Home Assistant:
        icon: home-assistant.svg
        href: https://ha.local.aleksanderbl.dk
        description: Open Source smart home platform

    - HyperHDR:
        icon: https://avatars.githubusercontent.com/u/69086569?s=48&v=4
        href: https://hyperhdr.local.aleksanderbl.dk
        description: Sejt lys bag fjernsynet

- Services:
    - Jellyfin:
        icon: jellyfin.svg
        href: https://jellyfin.local.aleksanderbl.dk
        # description: Jellyfin Media Server
        widget:
            type: jellyfin
            # url: https://192.168.207.207:8096
            url: "{{HOMEPAGE_VAR_JELLYFIN_IP}}"
            key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
            enableBlocks: true
            enableNowPlaying: false
    - Gitea:
        icon: gitea.svg
        href: https://git.local.aleksanderbl.dk
        description: Self hosted git service with Gitea

    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: https://uptime.local.aleksanderbl.dk
        description: Uptime Kuma
        # widget:
        #     type: uptimekuma
        #     url: https://uptime.local.aleksanderbl.dk
        #     key: "{{HOMEPAGE_VAR_UPTIMEKUMA_KEY}}"

- Infrastructure:
    - PiHole:
        icon: pi-hole.svg # icons found here https://github.com/walkxcode/dashboard-icons
        href: https://pihole1.local.aleksanderbl.dk
        # description: PiHole1
        # server: rpi4-1
        # container: pihole
        widget:
            type: pihole
            url: http://192.168.99.2:908
            key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
    - Traefik:
        icon: traefik.svg
        href: https://traefik-dashboard.local.aleksanderbl.dk
        description: Traefik Dashboard
        # widget:
        #     type: traefik
            # url: https://traefik-dashboard.local.aleksanderbl.dk
        # server: rpi4-1
        # container: traefik
    - Watchtower:
        icon: watchtower.svg
        description: Watchtower
        # server: rpi4-1
        # container: watchtower
    # - Cloudflare Tunnel:
    #     icon: cloudflare.svg
    #     widget:
    #         type: cloudflared
    #         accountid: "{{HOMEPAGE_VAR_CF_ACCOUNTID}}"
    #         tunnelid: "{{HOMEPAGE_VAR_CF_TUNNELID}}"
    #         key: "{{HOMEPAGE_VAR_CF_KEY}}"


- Social:
    - LittleLink:
        icon: mdi-link-box-variant
        href: https://links.local.aleksanderbl.dk
        # server: rpi4-1
    - CV:
        icon: mdi-account-card
        href: https://cv.aleksanderbl.dk

    - Github:
        icon: mdi-github
        href: https://github.com/aleksanderbl29

    # - widget:
    #     type: gatus
    #     url: https://gatus.local.aleksanderbl.dk

- Development:
    - OLLamas:
        icon: mdi-llama
        href: http://localhost:3000

    - Quarto Preview:
        icon: mdi-book-arrow-up-outline
        href: http://localhost:4200
