---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Homelab Dashboard

background: https://images.unsplash.com/photo-1551309292-e185c0b6e22a?q=80&w=2938&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
