name: Automatic issue list in Readme
on:
  workflow_dispatch:
  issues:
    types: [opened, edited, milestoned, demilestoned, closed, reopened, assigned, unassigned, labeled, unlabeled]
  push:
    branches:
      - main

jobs:
  auto-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rewriteReadme
        uses: seed-of-apricot/issue-list-readme@v1.1.0
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '<!-- issueTable -->'
          labels: 'Working on it'
          state: 'open'
      - name: add
        run: git add README.md
      - name: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          message: 'Update README.md with latest issues'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}