---
name: Docker-Test
'on':
  pull_request:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-test.yml'
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: git pull
      #   run: |
      #     git pull origin main
      - name: setup docker environment
        run: |
          docker network create proxy
          docker network create media
          docker network create external
          docker volume create --name=portainer_data
          docker volume create --name=uptimekuma-data
          cd cloudflare-tunnel && touch .env
      - name: cloudflared
        run: |
          cd cloudflare-tunnel && docker-compose up -d
      - name: homer
        run: |
          cd homer && docker-compose up -d
      - name: littlelink
        run: |
          cd littlelink-server && docker-compose up -d
      - name: portainer-traefik
        run: |
          cd portainer-traefik && docker-compose up -d
      - name: uptime-kuma
        run: |
          cd uptime-kuma && docker-compose up -d
      - name: watchtower
        run: |
          cd watchtower && docker-compose up -d
  Bind9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: git pull
      #   run: |
      #     git pull origin main
      - name: setup docker environment
        run: |
          docker network create proxy
          docker network create media
          docker network create external
          docker volume create --name=portainer_data
          docker volume create --name=uptimekuma-data
          cd cloudflare-tunnel && touch .env
      - name: bind9
        run: |
          cd bind9 && docker-compose up -d
  pihole:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: git pull
      #   run: |
      #     git pull origin main
      - name: setup docker environment
        run: |
          docker network create proxy
          docker network create media
          docker network create external
          docker volume create --name=portainer_data
          docker volume create --name=uptimekuma-data
          cd cloudflare-tunnel && touch .env
      - name: pihole
        run: |
          cd pihole/pihole-docker && docker-compose up -d
