---
name: Yaml Lint
'on': pull_request
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1
        with:
          config: "./custom/.yamllint"
