---
name: Portainer agent deploy
'on':
  push:
    branches:
      - 'main'
    paths:
      - 'portainer-agent/**'
      - '.github/workflows/ha-pi-deploy.yml'

jobs:
  Deployment:
    runs-on: rpi4
    steps:
      - name: Update local git
        shell: sh
        run: |
          cd /home/aleksanderbang-larsen/homelab
          git pull
      - name: Deploy stack
        shell: sh
        run: |
          cd
          cd /home/aleksanderbang-larsen/homelab/portainer-agent
          docker-compose up -d --force-recreate
      # - name: Check DNS
      #   shell: sh
      #   run: |
      #     nslookup traefik-dashboard.local.aleksanderbl.dk 127.0.0.1
      #     nslookup portainer.local.aleksanderbl.dk 127.0.0.1
