---
  name: HomeAssistant config pull
  'on':
    push:
      branches:
        - 'main'
      paths:
        - 'home-assistant/**'
        - '.github/workflows/homeassistant.yml'
    schedule:
      - cron: '30 * * * *'

  jobs:
    Deployment:
      runs-on: rpi4
      steps:
        - name: Update local git
          shell: sh
          run: |
            cd /home/aleksanderbang-larsen/homeassistant-config
            git pull
