---
name: OCI-Deployment
'on':
  push:
    branches:
      - main
    paths:
      - 'oci/*'
      - '.github/workflows/oci-deployment.yml'
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup docker environment
        run: |
          docker network create proxy
          docker volume create --name=portainer_data
          docker volume create --name=uptimekuma-data
      - name: deploy
        run: |
          cd oci && docker-compose up -d
  git_pull:
    runs-on: oracle-cloud
    needs: Testing
    steps:
      - name: git pull
        shell: sh
        run: |
          cd
          cd homelab
          git pull
          cd
          cd CV
          git pull
  deploy:
    runs-on: oracle-cloud
    needs: [git_pull, Testing]
    steps:
      - name: deploy
        shell: sh
        run: |
          cd
          cd homelab/oci
          docker-compose up -d --force-recreate
