name: OCI-Deployment
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'oci/*'
      - '.github/workflows/oci-deployment.yml'
jobs:
  git_pull:
    runs-on: oracle-cloud
    steps:
      - name: git pull
        shell: sh
        run: |
          cd
          cd homelab
          git pull
  deploy:
    runs-on: oracle-cloud
    needs: git_pull
    steps:
      - name: deploy
        shell: sh
        run: |
          cd
          cd homelab/oci
          docker-compose up -d --force-recreate