---
name: Docker-Deployment
'on':
  push:
    branches:
      - main
    paths:
      - 'littlelink-server/**'
      - 'uptime-kuma/**'
      - 'watchtower/**'
      - '.github/workflows/portainer-deploy.yml'
      - 'dashboard/**'
      - 'development/**'

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: git pull
        run: |
          git pull origin main
      - name: setup docker environment
        run: |
          docker network create proxy
          docker volume create --name=portainer_data
          docker volume create --name=uptimekuma-data
      - name: littlelink
        run: |
          cd littlelink-server && docker-compose up -d
      - name: portainer-traefik
        run: |
          cd portainer-traefik && docker-compose up -d
      - name: uptime-kuma
        run: |
          cd uptime-kuma && docker-compose up -d
      - name: watchtower
        run: |
          cd watchtower && docker-compose up -d
      - name: dashboard
        run: |
          cd dashboard && docker-compose up -d
  littlelink:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^littlelink-server/' -and $_ -match '.yml$' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "docker-compose-changed"
          Write-Host "::set-output name=docker-compose-changed::$HasDiff"

      # Run the step only if "docker-compose-changed" equals "True"
      - uses: joelwmale/webhook-action@2.3.2
        # steps.<step_id>.outputs.<output name>
        if: steps.check_file_changed.outputs.docker-compose-changed == 'True'
        with:
          url: ${{env.LITTLELINK_PORTAINER_WEBHOOK}}
        env:
          LITTLELINK_PORTAINER_WEBHOOK: ${{secrets.LITTLELINK_PORTAINER_WEBHOOK}}

  Uptime-Kuma:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^uptime-kuma/' -and $_ -match '.yml$' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "docker-compose-changed"
          Write-Host "::set-output name=docker-compose-changed::$HasDiff"

      # Run the step only if "docker-compose-changed" equals "True"
      - uses: joelwmale/webhook-action@2.3.2
        # steps.<step_id>.outputs.<output name>
        if: steps.check_file_changed.outputs.docker-compose-changed == 'True'
        with:
          url: ${{env.UPTIME_KUMA_PORTAINER_WEBHOOK}}
        env:
          UPTIME_KUMA_PORTAINER_WEBHOOK: ${{secrets.UPTIME_KUMA_PORTAINER_SECRET}}

  Watchtower:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^watchtower/' -and $_ -match '.yml$' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "docker-compose-changed"
          Write-Host "::set-output name=docker-compose-changed::$HasDiff"

      # Run the step only if "docker-compose-changed" equals "True"
      - uses: joelwmale/webhook-action@2.3.2
        # steps.<step_id>.outputs.<output name>
        if: steps.check_file_changed.outputs.docker-compose-changed == 'True'
        with:
          url: ${{env.WATCHTOWER_PORTAINER_WEBHOOK}}
        env:
          WATCHTOWER_PORTAINER_WEBHOOK: ${{secrets.WATCHTOWER_PORTAINER_SECRET}}

  Testing-deployment:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^development/' -and $_ -match '.yml$' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "docker-compose-changed"
          Write-Host "::set-output name=docker-compose-changed::$HasDiff"

      # Run the step only if "docker-compose-changed" equals "True"
      - uses: joelwmale/webhook-action@2.3.2
        # steps.<step_id>.outputs.<output name>
        if: steps.check_file_changed.outputs.docker-compose-changed == 'True'
        with:
          url: ${{env.DEVELOPMENT_PORTAINER_WEBHOOK}}
        env:
          DEVELOPMENT_PORTAINER_WEBHOOK: ${{secrets.DEVELOPMENT_PORTAINER_SECRET}}

  Dashboard:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^dashboard/' -and $_ -match '.yml$' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "docker-compose-changed"
          Write-Host "::set-output name=docker-compose-changed::$HasDiff"

      # Run the step only if "docker-compose-changed" equals "True"
      - uses: joelwmale/webhook-action@2.3.2
        # steps.<step_id>.outputs.<output name>
        if: steps.check_file_changed.outputs.docker-compose-changed == 'True'
        with:
          url: ${{env.DASHBOARD_PORTAINER_WEBHOOK}}
        env:
          DASHBOARD_PORTAINER_WEBHOOK: ${{secrets.DASHBOARD_PORTAINER_SECRET}}
