name: testing
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/auto-issue.yml'
      - '.github/workflows/selfhost-deploy.yml'
      - '.github/dependabot.yml'
      - 'portainer-traefik/**'

jobs:
  # Littlelink-Server:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       # Checkout as many commits as needed for the diff
  #       fetch-depth: 2
  #   - shell: sh
  #     # Give an id to the step, so we can reference it later
  #     id: check_file_changed
  #     run: |
  #       # Diff HEAD with the previous commit
  #       $diff = git diff --name-only HEAD^ HEAD

  #       # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
  #       $SourceDiff = $diff | Where-Object { $_ -match '^littlelink-server/' -and $_ -match '.yml$' }
  #       $HasDiff = $SourceDiff.Length -gt 0

  #       # Set the output named "docker-compose-changed"
  #       Write-Host "::set-output name=docker-compose-changed::$HasDiff"

  # littlelink-server-changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     changes: ${{ steps.check_for_changes.outputs.changes }}
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Get changed files
  #     id: changed-files
  #     uses: tj-actions/changed-files@v36
  #   - name: output changed files
  #     id: check_for_changes
  #     run: |
  #       echo "changed files: ${{ steps.changed-files.outputs.files }}"
  #       echo "::set-output name=changes::${{ steps.changed-files.outputs.files }}"

  redeploy:
    runs-on: self-hosted
    steps:
    - uses: joelwmale/webhook-action@2.3.2
      name: littlelink-server
      with:
        url: ${{env.LITTLELINK_PORTAINER_WEBHOOK}}
        insecure: true
      env:
        LITTLELINK_PORTAINER_WEBHOOK: ${{secrets.LITTLELINK_PORTAINER_WEBHOOK}}
    - uses: joelwmale/webhook-action@2.3.2
      name: uptime-kuma
      with:
        url: ${{env.UPTIME_KUMA_PORTAINER_WEBHOOK}}
        insecure: true
      env:
        UPTIME_KUMA_PORTAINER_WEBHOOK: ${{secrets.UPTIME_KUMA_PORTAINER_SECRET}}
    - uses: joelwmale/webhook-action@2.3.2
      name: watchtower
      with:
        url: ${{env.WATCHTOWER_PORTAINER_WEBHOOK}}
        insecure: true
      env:
        WATCHTOWER_PORTAINER_WEBHOOK: ${{secrets.WATCHTOWER_PORTAINER_SECRET}}


        # jobs:
        #   job1:
        #     runs-on: ubuntu-latest
        #     # Map a step output to a job output
        #     outputs:
        #       output1: ${{ steps.step1.outputs.test }}
        #       output2: ${{ steps.step2.outputs.test }}
        #     steps:
        #       - id: step1
        #         run: echo "test=hello" >> "$GITHUB_OUTPUT"
        #       - id: step2
        #         run: echo "test=world" >> "$GITHUB_OUTPUT"
        #   job2:
        #     runs-on: ubuntu-latest
        #     needs: job1
        #     steps:
        #       - env:
        #           OUTPUT1: ${{needs.job1.outputs.output1}}
        #           OUTPUT2: ${{needs.job1.outputs.output2}}
        #         run: echo "$OUTPUT1 $OUTPUT2"
