name: Portainer Redeploy w. Webhook
on:
  push:
    branches:
      - 'main'

jobs:
  Littlelink-Server:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '^littlelink-server/' -and $_ -match '.yml$' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docker-compose-changed"
        Write-Host "::set-output name=docker-compose-changed::$HasDiff"

    # Run the step only if "docker-compose-changed" equals "True"
    - uses: joelwmale/webhook-action@2.3.2
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.docker-compose-changed == 'True'
      with:
        url: ${LITTLELINK_PORTAINER_WEBHOOK}
      env:
        LITTLELINK_PORTAINER_WEBHOOK: ${{ secrets.LITTLELINK_PORTAINER_WEBHOOK }}


  Uptime-Kuma:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '^uptime-kuma/' -and $_ -match '.yml$' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docker-compose-changed"
        Write-Host "::set-output name=docker-compose-changed::$HasDiff"

    # Run the step only if "docker-compose-changed" equals "True"
    - uses: joelwmale/webhook-action@2.3.2
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.docker-compose-changed == 'True'
      with:
          url: ${UPTIME_KUMA_PORTAINER_WEBHOOK}
      env:
        UPTIME_KUMA_PORTAINER_WEBHOOK: ${{ secrets.UPTIME_KUMA_PORTAINER_WEBHOOK }}

  Watchtower:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '^watchtower/' -and $_ -match '.yml$' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docker-compose-changed"
        Write-Host "::set-output name=docker-compose-changed::$HasDiff"

    # Run the step only if "docker-compose-changed" equals "True"
    - uses: joelwmale/webhook-action@2.3.2
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.docker-compose-changed == 'True'
      with:
          url: ${WATCHTOWER_PORTAINER_WEBHOOK}
      env:
        WATCHTOWER_PORTAINER_WEBHOOK: ${{ secrets.WATCHTOWER_PORTAINER_WEBHOOK }}

#webhook:
#    name: "call webhook"
#    runs-on: ubuntu-latest
#    steps:
#      - name: Littlelink Webhook
#        uses: joelwmale/webhook-action@2.3.2
#        with:
#          url: https://192.168.99.5:9443/api/stacks/webhooks/8f2c2f31-f57a-4e94-9132-b610b19015ca
#
#      - name: UptimeKuma Webhook
#        uses: joelwmale/webhook-action@2.3.2
#        with:
#          url: https://192.168.99.5:9443/api/stacks/webhooks/4916ef88-d5b2-4019-a2e7-faeec3fb71ea



#  conditional_step:
#    runs-on: 'ubuntu-20.04'
#    steps:
#    - uses: actions/checkout@v2
#      with:
#        # Checkout as many commits as needed for the diff
#        fetch-depth: 2
#    - shell: pwsh
#      # Give an id to the step, so we can reference it later
#      id: check_file_changed
#      run: |
#        # Diff HEAD with the previous commit
#        $diff = git diff --name-only HEAD^ HEAD
#
#        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
#        $SourceDiff = $diff | Where-Object { $_ -match '^littlelink-server/' -and $_ -match '.yml$' }
#        $HasDiff = $SourceDiff.Length -gt 0
#
#        # Set the output named "docker-compose-changed"
#        Write-Host "::set-output name=docker-compose-changed::$HasDiff"
#
#    # Run the step only if "docker-compose-changed" equals "True"
#    - shell: pwsh
#      # steps.<step_id>.outputs.<output name>
#      if: steps.check_file_changed.outputs.docker-compose-changed == 'True'
