---
version: '3'

services:
  mysql:
    restart: unless-stopped
    image: mysql:8.3
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - semaphore
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: ${DB_USER}
      SEMAPHORE_DB_PASS: ${DB_PASSWORD}
      SEMAPHORE_DB_HOST: mysql     # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 3306     # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql     # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
    volumes:
      - ~/deployment/cd.inventory.ini/:/tmp/semaphore/cd.inventory.ini:ro
      - ~/ansible4homelab:/tmp/semaphore/ansible4homelab:ro
    depends_on:
      - mysql     # for postgres, change to: postgres
    networks:
      - semaphore
      - proxy
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env

    labels:
      traefik.enable: 'true'
      traefik.http.routers.semaphore.entrypoints: http
      traefik.http.routers.semaphore.rule: Host(`semaphore.local.aleksanderbl.dk`)
      traefik.http.middlewares.semaphore-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.semaphore.middlewares: semaphore-https-redirect
      traefik.http.routers.semaphore-secure.entrypoints: https
      traefik.http.routers.semaphore-secure.rule: Host(`semaphore.local.aleksanderbl.dk`)
      traefik.http.routers.semaphore-secure.tls: true
      traefik.http.routers.semaphore-secure.service: semaphore
      traefik.http.services.semaphore.loadbalancer.server.port: 3000
      traefik.docker.network: proxy

      com.centurylinklabs.watchtower.monitor-only: true

volumes:
  semaphore-mysql:     # to use postgres, switch to: semaphore-postgres

networks:
  proxy:
    external: true
  semaphore:
